name: app_tests

on: [pull_request]

jobs:
  run_tests:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.app && /usr/bin/xcodebuild -version
    - name: Run tests
      run: xcodebuild test -scheme Chessbic -project Chessbic.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14' | xcpretty -s && exit ${PIPESTATUS[0]}
